### ISSUE TITLE
Support access control

### ISSUE THREAD

**Issue by kenchan0130** [softwaremill/stringmask#4]
## Expected behavior
I expected to apply mask for case class with access control.

## Steps to reproduce the behavior

```scala
@customize
private[config] Password(@mask value: String)
```

```log
[error] /path/to/project/config/Password.scala: Unsupported case class type. Cannot rewrite toString().
[error] @customize
[error]  ^
```

## Workaround

Without access control.

```scala
@customize
Password(@mask value: String)
```

**Comment by kciesielski** [comment]
Thanks a lot for reporting, @kenchan0130! [Version 1.3.0](https://github.com/softwaremill/stringmask/releases/tag/v1.3.0) with access control support is now on its way to Maven Central.

**Comment by kenchan0130** [comment]
@kciesielski 

Thank you your support!
I am very happy!

By the way, do not you have to worry about `protected`?
I have no immediate problems. Because I became anxious, I did a comment.

**Comment by kciesielski** [comment]
@kenchan0130 you mean `protected[pkg] case class`? It's quite uncommon, because it means effectively the same, so no worries for now.

**Comment by kenchan0130** [comment]
Yes.
I knew it.
